# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7003d54001e04290703b2da00249fffe9cfe0cd02bcfb5b301b6332b7515721fadb3f602bf3341cb62372c4b2fb25a4b70557e5b253b209451620e1672d23957

test:
  secret_key_base: e9e149e4c5891773ccf743fd4e9c5a85d67c9b01badd550576d59f771585b2dc8ac70336a345d573687d7090ece1172877bb12ab77df9356c555cecfc5ec5295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
